---
- name: Create the Node Exporter group
  group:
    name: "{{ prometheus_node_exporter_service_group }}"
    state: present
    system: true

- name: Create the Node Exporter user
  user:
    name: "{{ prometheus_node_exporter_service_username }}"
    groups: "{{ prometheus_node_exporter_service_group }}"
    append: true
    shell: /usr/sbin/nologin
    create_home: false
  when: prometheus_node_exporter_manage_user

# Install Prometheus Node Exporter
#
- name: Check if the version of Node Exporter already exists
  stat:
    path: "/usr/local/bin/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64"
  register: prometheus_node_exporter_install_path

- name: Download Node Exporter
  get_url:
    url: "{{ prometheus_node_exporter_download_url }}"
    dest: "/root/node_exporter-{{ prometheus_node_exporter_version }}.tar.gz"
  when: not prometheus_node_exporter_install_path.stat.exists

- name: Extract Node Exporter
  unarchive:
    src: "/root/node_exporter-{{ prometheus_node_exporter_version }}.tar.gz"
    dest: "/root/"
    copy: false
    owner: root
    group: root
  when: not prometheus_node_exporter_install_path.stat.exists

- name: Copy file into final directory
  copy:
    remote_src: true
    src: "/root/node_exporter-{{ prometheus_node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    owner: "{{ prometheus_node_exporter_service_username }}"
    group: "{{ prometheus_node_exporter_service_group }}"
    mode: 0755
  when: not prometheus_node_exporter_install_path.stat.exists


- name: Copy the Node Exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart node_exporter

- name: Ensure Node Exporter is started and enabled on boot
  service:
    name: node_exporter
    state: started
    enabled: true
